\."#################################################################
\."$Id: genders_load_data.3,v 1.1 2003-04-18 22:37:12 achu Exp $
\."by Albert Chu <chu11@llnl.gov>
\."#################################################################
.\"
.TH GENDERS_OPEN 3 "Release 1.1" "LLNL" "LIBGENDERS"
.SH NAME
genders_open \- open, read, and parse a genders file 
.SH SYNOPSIS
.B #include <genders.h>
.sp
.BI "int genders_open(genders_t handle, char *filename);"
.br
.SH DESCRIPTION
\fBgenders_open()\fR opens, read, and parses the genders file
indicated by \fIfilename\fR.  If \fIfilename\fR is NULL,
\fBgenders_open()\fR will attempt to open, read, and parse the default
genders file defined by
\fBDEFAULT_GENDERS_FILE\fR. \fIhandle\fR is a genders handle created
by
.BR genders_handle_create (3).  

After \fBgenders_open()\fR is called, information about the genders
file is stored in the genders handle passed in.  This information is
used by other genders C API functions.  All future use of \fIhandle\fR
with other genders C API functions will be directly associated with
the genders file indicated by \fIfilename\fR (or the default genders
file if \fIfilename\fR is NULL).
.br
.SH RETURN VALUES
On success, 0 is returned.  On error, -1 is returned, and an error code
is returned in \fIhandle\fR.  The error code can be retrieved
via
.BR genders_errnum (3)
, and a description of the error code can be retrieved via 
.BR genders_strerror (3).  
Error codes are defined in genders.h.
.br
.SH ERRORS
.TP
.B GENDERS_ERR_OPEN
The genders file indicated by \fIfilename\fR cannot be opened for reading.
.TP
.B GENDERS_ERR_PARSE
The genders file indicated by \fIfilename\fR is incorrectly formatted.
.TP
.B GENDERS_ERR_NOTCLOSED 
.BR genders_open (3) 
has already been called with \fIhandle\fR.  Before 
this genders handle can be associated with a new file,
.BR genders_close (3)
must be called to close the previous file associated with \fIhandle\fR.
.TP
.B GENDERS_ERR_OUTMEM
.BR malloc (3)
has failed internally, system is out of memory.
.TP
.B GENDERS_ERR_MAGIC 
\fIhandle\fR has an incorrect magic number.  \fIhandle\fR does not point to a genders
handle or \fIhandle\fR has been destroyed by 
.BR genders_handle_destroy (3).
.TP
.B GENDERS_ERR_INTERNAL
An internal system error has occurred.  
.br
.SH FILES
/usr/include/genders.h
.SH SEE ALSO
libgenders(3), genders_handle_create(3), genders_handle_destroy(3),
genders_errnum(3), genders_strerror(3)
