\."#################################################################
\."$Id: genders_getnodename.3,v 1.1 2003-04-18 22:37:12 achu Exp $
\."by Albert Chu <chu11@llnl.gov>
\."#################################################################
.\"
.TH GENDERS_GETNODENAME 3 "Release 1.1" "LLNL" "LIBGENDERS"
.SH NAME
genders_getnodename \- get the current node name
.SH SYNOPSIS
.B #include <genders.h>
.sp
.BI "int genders_getnodename(genders_t handle, char *node, int len);"
.br
.SH DESCRIPTION
\fBgenders_getnodename()\fR retrieves the name of the node that the
function is being called from.  The node name is stored in the buffer pointed
to be \fInode\fR.  \fIlen\fR should indicate the length of the buffer.   The node returned
by \fBgenders_getnodename()\fR is the shortened hostname of the node.  

To avoid passing in a buffer that is not large enough to store the node name, 
.BR genders_getmaxnodelen (3)
should be used to determine the minimum buffer size that should be used. 
.br
.SH RETURN VALUES
On success, 0 is returned.  On error, -1 is returned, and an error code
is returned in \fIhandle\fR.  The error code can be retrieved
via
.BR genders_errnum (3)
, and a description of the error code can be retrieved via 
.BR genders_strerror (3).  
Error codes are defined in genders.h.
.br
.SH ERRORS
.TP
.B GENDERS_ERR_NOTOPEN
.BR genders_open (3)
has not been called and an open genders file has not been associated with \fIhandle\fR.  
.TP
.B GENDERS_ERR_OVERFLOW
The buffer pointed to by \fInode\fR is not large enough to store the node name.
.TP
.B GENDERS_ERR_PARAMETERS
An incorrect parameter has been passed in.  
.TP
.B GENDERS_ERR_MAGIC 
\fIhandle\fR has an incorrect magic number.  \fIhandle\fR does not point to a genders
handle or \fIhandle\fR has been destroyed by 
.BR genders_handle_destroy (3).
.br
.SH FILES
/usr/include/genders.h
.SH SEE ALSO
libgenders(3), genders_open(3), genders_getmaxnodelen(3), genders_errnum(3), genders_strerror(3)
