\."#################################################################
\."$Id: genders_getattr_all.3,v 1.6 2003-08-18 22:45:50 achu Exp $
\."by Albert Chu <chu11@llnl.gov>
\."#################################################################
.\"
.TH GENDERS_GETATTR_ALL 3 "August 2003" "LLNL" "LIBGENDERS"
.SH NAME
genders_getattr_all \- get all the attributes stored in a genders file
.SH SYNOPSIS
.B #include <genders.h>
.sp
.BI "int genders_getattr_all(genders_t handle, char *attrs[], int len);"
.br
.SH DESCRIPTION
\fBgenders_getattr_all()\fR gets all the attributes found in the
genders file associated with \fIhandle\fR.  The attributes are stored
in the attribute list pointed to by \fIattrs\fR.  \fIlen\fR should
indicate the number of elements that can be stored in the attribute
list.

To avoid passing in a list that is not large enough to store all the
attributes,
.BR genders_getnumattrs (3)
should be used to determine the minimum number of elements \fIattrs\fR
should be able to store.
.BR genders_attrlist_create (3) 
could be used to create a list that is guaranteed to be large enough
to store all attributes.
.br
.SH RETURN VALUES
On success, the number of attributes stored in \fIattrs\fR is
returned.  On error, -1 is returned, and an error code is returned in
\fIhandle\fR.  The error code can be retrieved via
.BR genders_errnum (3)
, and a description of the error code can be retrieved via 
.BR genders_strerror (3).  
Error codes are defined in genders.h.
.br
.SH ERRORS
.TP
.B GENDERS_ERR_NULLHANDLE
The \fIhandle\fR parameter is NULL.  The genders handle must be
created with
.BR genders_handle_create (3).
.TP
.B GENDERS_ERR_NOTLOADED
.BR genders_load_data (3)
has not been called to load genders data.
.TP
.B GENDERS_ERR_OVERFLOW
The list pointed to by \fIattrs\fR is not large enough to store all
the attributes.
.TP
.B GENDERS_ERR_PARAMETERS
An incorrect parameter has been passed in.  
.TP
.B GENDERS_ERR_NULLPTR
A null pointer has been found in the list passed in.
.TP
.B GENDERS_ERR_MAGIC 
\fIhandle\fR has an incorrect magic number.  \fIhandle\fR does not
point to a genders handle or \fIhandle\fR has been destroyed by
.BR genders_handle_destroy (3).
.br
.SH FILES
/usr/include/genders.h
.SH SEE ALSO
libgenders(3), genders_handle_create(3), genders_load_data(3),
genders_getnumattrs(3), genders_attrlist_create(3), genders_errnum(3),
genders_strerror(3)
