\."#################################################################
\."$Id: genders_handle_destroy.3,v 1.1 2003-04-18 22:37:12 achu Exp $
\."by Albert Chu <chu11@llnl.gov>
\."#################################################################
.\"
.TH GENDERS_HANDLE_DESTROY 3 "Release 1.1" "LLNL" "LIBGENDERS"
.SH NAME
genders_handle_destroy \- destroys a genders handle
.SH SYNOPSIS
.B #include <genders.h>
.sp
.BI "int genders_handle_destroy(genders_t handle);"
.br
.SH DESCRIPTION
\fBgenders_handle_destroy()\fR destroys the genders handle pointed to by
\fIhandle\fR and frees all allocated memory associated with it.
.br
.SH RETURN VALUES
On success, 0 is returned.  On error, -1 is returned, and an error code
is returned in \fIhandle\fR.  The error code can be retrieved
via
.BR genders_errnum (3)
, and a description of the error code can be retrieved via 
.BR genders_strerror (3).  
Error codes are defined in genders.h.
.br
.SH ERRORS
.TP
.B GENDERS_ERR_NOTCLOSED 
.BR genders_close (3)
has not been called to close a genders file associated with \fIhandle\fR.
.TP
.B GENDERS_ERR_MAGIC 
\fIhandle\fR has an incorrect magic number.  \fIhandle\fR does not point to a genders
handle or \fIhandle\fR has already been destroyed.
.br
.SH FILES
/usr/include/genders.h
.SH SEE ALSO
libgenders(3), genders_handle_create(3), genders_open(3),
genders_errnum(3), genders_strerror(3)
