.\"############################################################################
.\"  $Id: genders_handle_destroy.3,v 1.12 2010-02-02 00:04:34 chu11 Exp $
.\"############################################################################
.\"  Copyright (C) 2007-2019 Lawrence Livermore National Security, LLC.
.\"  Copyright (C) 2001-2007 The Regents of the University of California.
.\"  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
.\"  Written by Jim Garlick <garlick@llnl.gov> and Albert Chu <chu11@llnl.gov>.
.\"  UCRL-CODE-2003-004.
.\"  
.\"  This file is part of Genders, a cluster configuration database.
.\"  For details, see <http://www.llnl.gov/linux/genders/>.
.\"  
.\"  Genders is free software; you can redistribute it and/or modify it under
.\"  the terms of the GNU General Public License as published by the Free
.\"  Software Foundation; either version 2 of the License, or (at your option)
.\"  any later version.
.\"  
.\"  Genders is distributed in the hope that it will be useful, but WITHOUT ANY
.\"  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
.\"  FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
.\"  details.
.\"  
.\"  You should have received a copy of the GNU General Public License along
.\"  with Genders.  If not, see <http://www.gnu.org/licenses/>.
.\"############################################################################
.TH GENDERS_HANDLE_DESTROY 3 "August 2003" "LLNL" "LIBGENDERS"
.SH NAME
genders_handle_destroy \- destroys a genders handle
.SH SYNOPSIS
.B #include <genders.h>
.sp
.BI "int genders_handle_destroy(genders_t handle);"
.br
.SH DESCRIPTION
\fBgenders_handle_destroy()\fR destroys the genders handle pointed to
by \fIhandle\fR and frees all allocated memory associated with it.
.br
.SH RETURN VALUES
On success, 0 is returned.  On error, -1 is returned, and an error
code is returned in \fIhandle\fR.  The error code can be retrieved via
.BR genders_errnum (3)
, and a description of the error code can be retrieved via 
.BR genders_strerror (3).  
Error codes are defined in genders.h.
.br
.SH ERRORS
.TP
.B GENDERS_ERR_NULLHANDLE
The \fIhandle\fR parameter is NULL.  The genders handle must be
created with
.BR genders_handle_create (3).
.TP
.B GENDERS_ERR_MAGIC 
\fIhandle\fR has an incorrect magic number.  \fIhandle\fR does not
point to a genders handle or \fIhandle\fR has already been destroyed.
.br
.SH FILES
/usr/include/genders.h
.SH SEE ALSO
libgenders(3), genders_handle_create(3), genders_load_data(3),
genders_errnum(3), genders_strerror(3)
