.\"############################################################################
.\"  $Id: genders_getattr_all.3,v 1.12 2010-02-02 00:04:34 chu11 Exp $
.\"############################################################################
.\"  Copyright (C) 2007-2019 Lawrence Livermore National Security, LLC.
.\"  Copyright (C) 2001-2007 The Regents of the University of California.
.\"  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
.\"  Written by Jim Garlick <garlick@llnl.gov> and Albert Chu <chu11@llnl.gov>.
.\"  UCRL-CODE-2003-004.
.\"  
.\"  This file is part of Genders, a cluster configuration database.
.\"  For details, see <http://www.llnl.gov/linux/genders/>.
.\"  
.\"  Genders is free software; you can redistribute it and/or modify it under
.\"  the terms of the GNU General Public License as published by the Free
.\"  Software Foundation; either version 2 of the License, or (at your option)
.\"  any later version.
.\"  
.\"  Genders is distributed in the hope that it will be useful, but WITHOUT ANY
.\"  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
.\"  FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
.\"  details.
.\"  
.\"  You should have received a copy of the GNU General Public License along
.\"  with Genders.  If not, see <http://www.gnu.org/licenses/>.
.\"############################################################################
.TH GENDERS_GETATTR_ALL 3 "August 2003" "LLNL" "LIBGENDERS"
.SH NAME
genders_getattr_all \- get all the attributes stored in a genders file
.SH SYNOPSIS
.B #include <genders.h>
.sp
.BI "int genders_getattr_all(genders_t handle, char *attrs[], int len);"
.br
.SH DESCRIPTION
\fBgenders_getattr_all()\fR gets all the attributes found in the
genders file associated with \fIhandle\fR.  The attributes are stored
in the attribute list pointed to by \fIattrs\fR.  \fIlen\fR should
indicate the number of elements that can be stored in the attribute
list.

To avoid passing in a list that is not large enough to store all the
attributes,
.BR genders_getnumattrs (3)
should be used to determine the minimum number of elements \fIattrs\fR
should be able to store.
.BR genders_attrlist_create (3) 
could be used to create a list that is guaranteed to be large enough
to store all attributes.
.br
.SH RETURN VALUES
On success, the number of attributes stored in \fIattrs\fR is
returned.  On error, -1 is returned, and an error code is returned in
\fIhandle\fR.  The error code can be retrieved via
.BR genders_errnum (3)
, and a description of the error code can be retrieved via 
.BR genders_strerror (3).  
Error codes are defined in genders.h.
.br
.SH ERRORS
.TP
.B GENDERS_ERR_NULLHANDLE
The \fIhandle\fR parameter is NULL.  The genders handle must be
created with
.BR genders_handle_create (3).
.TP
.B GENDERS_ERR_NOTLOADED
.BR genders_load_data (3)
has not been called to load genders data.
.TP
.B GENDERS_ERR_OVERFLOW
The list pointed to by \fIattrs\fR is not large enough to store all
the attributes.
.TP
.B GENDERS_ERR_PARAMETERS
An incorrect parameter has been passed in.  
.TP
.B GENDERS_ERR_NULLPTR
A null pointer has been found in the list passed in.
.TP
.B GENDERS_ERR_MAGIC 
\fIhandle\fR has an incorrect magic number.  \fIhandle\fR does not
point to a genders handle or \fIhandle\fR has been destroyed by
.BR genders_handle_destroy (3).
.br
.SH FILES
/usr/include/genders.h
.SH SEE ALSO
libgenders(3), genders_handle_create(3), genders_load_data(3),
genders_getnumattrs(3), genders_attrlist_create(3), genders_errnum(3),
genders_strerror(3)
