\."#################################################################
\."$Id: genders_handle_create.3,v 1.3 2003-05-09 17:32:51 achu Exp $
\."by Albert Chu <chu11@llnl.gov>
\."#################################################################
.\"
.TH GENDERS_HANDLE_CREATE 3 "Release 1.1" "LLNL" "LIBGENDERS"
.SH NAME
genders_handle_create \- create a genders handle 
.SH SYNOPSIS
.B #include <genders.h>
.sp
.BI "genders_t genders_handle_create(void);"
.br
.SH DESCRIPTION
.br
\fBgenders_handle_create()\fR creates a genders handle for use with
the genders C API.  A genders handle is of type genders_t, which is
defined in genders.h.  The genders handle must be passed to most of
the genders C API functions.
.br
.SH RETURN VALUES
On success, a genders handle (datatype genders_t) will be returned. On
error, NULL is returned.
.br
.SH FILES
/usr/include/genders.h
.SH SEE ALSO
genders_handle_destroy(3), genders_load_data(3)
