\."#################################################################
\."$Id: libgenders.3,v 1.9 2003-08-18 22:45:50 achu Exp $
\."by Albert Chu <chu11@llnl.gov>
\."#################################################################
.\"
.TH LIBGENDERS 3 "August 2003" "LLNL" "LIBGENDERS"
.SH NAME
libgenders \- a library of functions to parse and retrieve genders data
.SH SYNOPSIS
.B #include <genders.h>
.sp
.BI "genders_t genders_handle_create(void);"
.sp
.BI "int genders_handle_destroy(genders_t handle);"
.sp
.BI "int genders_load_data(genders_t handle, const char *filename);"
.sp
.BI "int genders_errnum(genders_t handle);"
.sp
.BI "char *genders_strerror(int errnum);"
.sp
.BI "char *genders_errormsg(genders_t handle);"
.sp
.BI "void genders_perror(genders_t handle, const char *msg);"
.sp
.BI "int genders_getnumnodes(genders_t handle);"
.sp
.BI "int genders_getnumattrs(genders_t handle);"
.sp
.BI "int genders_getmaxattrs(genders_t handle);"
.sp
.BI "int genders_getmaxnodelen(genders_t handle);"
.sp
.BI "int genders_getmaxattrlen(genders_t handle);"
.sp
.BI "int genders_getmaxvallen(genders_t handle);"
.sp
.BI "int genders_nodelist_create(genders_t handle, char ***nodelist);"
.sp
.BI "int genders_nodelist_clear(genders_t handle, char **nodelist);"
.sp
.BI "int genders_nodelist_destroy(genders_t handle, char **nodelist);"
.sp
.BI "int genders_attrlist_create(genders_t handle, char ***attrlist);"
.sp
.BI "int genders_attrlist_clear(genders_t handle, char **attrlist);"
.sp
.BI "int genders_attrlist_destroy(genders_t handle, char **attrlist);"
.sp
.BI "int genders_vallist_create(genders_t handle, char ***vallist);"
.sp
.BI "int genders_vallist_clear(genders_t handle, char **vallist);"
.sp
.BI "int genders_vallist_destroy(genders_t handle, char **vallist);"
.sp
.BI "int genders_getnodename(genders_t handle, char *node, int len);"
.sp
.BI "int genders_getnodes(genders_t handle, char *nodes[], int len, const char *attr, const char *val);"
.sp
.BI "int genders_getattr(genders_t handle, char *attrs[], char *vals[], int len, const char *node);"
.sp
.BI "int genders_getattr_all(genders_t handle, char *attrs[], int len);"
.sp
.BI "int genders_testattr(genders_t handle, const char *node, const char *attr, char *val, int len);"
.sp
.BI "int genders_testattrval(genders_t handle, const char *node, const char *attr, const char *val);"
.sp
.BI "int genders_isnode(genders_t handle, const char *node);"
.sp
.BI "int genders_isattr(genders_t handle, const char *attr);"
.sp
.BI "int genders_isattrval(genders_t handle, const char *attr, const char *val);"
.sp
.BI "int genders_parse(genders_t handle, const char *filename, FILE *stream);"
.br
.SH DESCRIPTION
The genders library functions are a set of functions used to parse and
retrieve data from a genders file.  It is meant to be the C equivalent
to the original gendlib(3) perl library.  For instructions, please see
the individual manpages for each of the functions above, or read the
comments written in /usr/include/genders.h.
.br
.SH GENDERS FILE FORMAT
Each line of the genders file has the following format:

     nodename attr[=value],attr[=value],attr[=value],...

The nodename is the shortened hostname of a node and must be unique in
the genders file.  This is followed by any number of spaces or tabs,
and then the comma-separated list of attributes, each of which can
optionally have a value.  There must be no spaces embedded in the
attribute list and there is no provision for continuation lines.
Commas and equal characters are special and cannot appear in attribute
names or their values.  Comments are prefixed with the hash chracter
(#) and can appear anywhere in the file.  The active genders file is
typically found at /etc/genders or /admin/etc/genders.

Here is a rather undeveloped genders file from a small 8-node linux
cluster:

     slc0 elanid=8,passwdhost,nqsmgr
     slc1 elanid=9,nqscompute
     slc2 elanid=10,nqscompute
     slc3 elanid=11,nqscompute
     slc4 elanid=12,nqscompute
     slc5 elanid=13,nqscompute
     slc6 elanid=14,nqscompute
     slc7 elanid=15,nqscompute

.SH FILES
/usr/include/genders.h
.sp
/etc/genders
.SH SEE ALSO
Libgenders(3), Genders(3), genders_handle_create(3),
genders_handle_destroy(3), genders_load_data(3), genders_errnum(3),
genders_strerror(3), genders_errormsg(3), genders_perror(3),
genders_getnumnodes(3), genders_getnumattrs(3),
genders_getmaxattrs(3), genders_getmaxnodelen(3),
genders_getmaxattrlen(3), genders_getmaxvallen(3),
genders_nodelist_create(3), genders_nodelist_clear(3),
genders_nodelist_destroy(3), genders_attrlist_create(3),
genders_attrlist_clear(3), genders_attrlist_destroy(3),
genders_vallist_create(3), genders_vallist_clear(3),
genders_vallist_destroy(3), genders_getnodename(3),
genders_getnodes(3), genders_getattr(3), genders_getattr_all(3),
genders_testattr(3), genders_testattrval(3), genders_testnode(3),
genders_parse(3)
