#!/bin/sh
#
# Copy /etc/genders and /etc/clusters from /var/dist
#
if [ $# -ne 1 ]; then
	echo Usage: dist_bootstrap clustername
	exit 1
fi
CLUSTER=$1
cd /var/dist || exit 1

umask 022
install -m 444 genders/genders.$CLUSTER /etc/genders
install -m 444 genders/clusters /etc
