.\"
.\" $Id: dist_local.1,v 1.2 2001-07-14 05:36:52 garlick Exp $
.\" $Source: /g/g0/achu/temp/genders-cvsbackup-full/genders/dist_local.1,v $
.\"
.\" Copyright (C) 2000-2001 Regents of the University of California
.\" See the DISCLAIMER file distributed with this package.
.\"
.\" Author: Jim Garlick
.\" Adapted from IBM SP version for linux 4/00.
.\"
.TH DIST_LOCAL 1 "4/14/99" "LLNL" "DIST_LOCAL"
.SH NAME
dist_local \- local rdist script
.SH SYNOPSIS
.B dist_local
.I "[package[.fileset]] ..."
.SH DESCRIPTION
The purpose of 
.B dist_local
is to update files on the local node from the /var/dist rdist repository.
It simply executes
.B "dist2 -l"
on the local node.
.B "dist2"
in turn runs rdist against files located in the NFS-mounted rdist repository,
/var/dist.
.LP
All arguments are passed on to
.B "dist2."
Typically these include the names of packages/filesets to be updated.
Packages are groups of files managed by a single Distfile in /var/dist, and 
filesets are labels within Distfiles.  If no packages are specified, everything
in /var/dist updated.
.LP
.SH "SEE ALSO"
rdist(1), dist2(1)
