#!/bin/sh

#############################################################################
#  $Id: dist_bootstrap,v 1.4 2002-12-08 19:42:34 garlick Exp $
#############################################################################
#  Copyright (C) 2001-2002 The Regents of the University of California.
#  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
#  Written by Jim Garlick <garlick@llnl.gov>.
#  UCRL-CODE-2003-004.
#  
#  This file is part of Genders, a cluster configuration database and
#  rdist preprocessor.
#  For details, see <http://www.llnl.gov/linux/genders/>.
#  
#  Genders is free software; you can redistribute it and/or modify it under
#  the terms of the GNU General Public License as published by the Free
#  Software Foundation; either version 2 of the License, or (at your option)
#  any later version.
#  
#  Genders is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#  FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
#  details.
#  
#  You should have received a copy of the GNU General Public License along
#  with Genders; if not, write to the Free Software Foundation, Inc.,
#  59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
#############################################################################

#
# Copy /etc/genders and /etc/clusters from /var/dist
#
if [ $# -ne 1 ]; then
	echo Usage: dist_bootstrap clustername
	exit 1
fi
CLUSTER=$1
cd /var/dist || exit 1

umask 022
install -m 444 genders/genders.$CLUSTER /etc/genders
install -m 444 genders/clusters /etc
