.\"
.\" $Id: dist2.1,v 1.4 2002-05-31 15:56:45 garlick Exp $
.\" $Source: /g/g0/achu/temp/genders-cvsbackup-full/genders/dist2.1,v $
.\"
.\" Copyright (C) 2000-2001 Regents of the University of California
.\" See the DISCLAIMER file distributed with this package.
.\"
.\" Author: Jim Garlick
.\" Adapted from IBM SP version for linux 4/00.
.\"
.TH DIST2 1 "4/14/99" "LLNL" "DIST2"
.SH NAME
dist2 \- rdist wrapper
.SH SYNOPSIS
.B dist2
.I "[-o rdist_opts] [-c cluster] [-v [-n]] [-i] [node spec] [package.[fileset]...]"
.br
.B dist2
.I "[-o rdist_opts] [-c cluster] [-v [-n]] [-i] [node spec] -f Distfile"
.br
.SH DESCRIPTION
.B Dist2
is a wrapper for USC 
.B rdist
which adds a powerful macro capability based on the
.I "genders file,"
and abstracts a collection of Distfiles into an
.I "rdist repository"
made up of 
.I "packages"
and
.I "filesets."
It operates as follows:
.IP
1) Chdir to /var/dist (the rdist repository) and verify that the dummy file
VAR_DIST_IS_MOUNTED exists.
.IP
2) Determine the appropriate set of Distfiles corresponding to
.I packages
specified on the command line.  If packages are specified, select
Distfile.{package list}, otherwise Distfile.{all packages}.
.IP
3) Scan the Distfiles for macro references of the form ${attr_xyz} and
prepend macro definitions based on the content of the genders file.
In the example above, all nodes carrying the genders attribute 
.I xyz 
would be listed in the attr_xyz definition.
.IP
4) Send the resulting concatenation of Distfiles and macro definitions to
the
.B rdist
program.
.LP
Node specification options are
.I -w node1,node2,node3
or
.I -g genders_attribute
or
.I -l
.
In the absense of these options,
all nodes targeted by the preprocessed Distfile (potentially all nodes 
appearing in the genders file) are updated.
.LP
.I -w
limits the update to the listed nodes.  Always specify the name as it appears
in the genders file; generally the primary hostname as reported by the 
.B hostname
command.
.LP
.I -g
similarly selects the set of nodes that have the specified genders attribute.
.LP
.I -l
selects the local node.
.LP
.I -i
selects canonical hostnames (the left hand side of a genders file entry).
The default on the SP is to convert these "initial_hostname" values to 
"reliable_hostname" via the SDR.  Elsewhere, the conversion is based on
taking the value of an "altname" genders attribute, if any.  This option
defeats this conversion.
.LP
.I -v
is used for debugging Distfile problems.  When
.B rdist
reports a syntax error, it refers to line numbers in the preprocessed
Distfile.  This option provides a means for the Distfile author to see
the preprocessed version.  If 
.I -n 
is also specified, line numbers will be prepended to each line.
.LP
/var/dist is actually used to manage rdisted files across several MPP systems.
We refer to each MPP as a
.I cluster,
with the file /etc/clusters mapping hostnames to cluster names.  
Distfile macros of the form ${attr_xyz} implicitly refer to the local cluster.
Specific clusters can be targeted by specifying a macro of the
form ${clustername!attr_xyz}.  These definitions expand to empty lists on
clusters other than the one specified.
.LP
Put another way, ${attr_xyz} refers all nodes in all clusters with the 
.I xyz
attribute, while ${clustername!attr_xyz} only refers to the nodes in 
.I clustername
with the 
.I xyz
attribute.
.LP
.SH "BUGS"
When expanding macros, we actually refer to /var/dist/genders/genders.cluster
instead of the installed version, /etc/genders.  Since the genders file
is under rdist control, referring directly to the source file eliminates a
potential bootstrapping problem.  On the other hand, it's ugly to hardcode
the source path, and we refer to other files, such as /etc/clusters,
in their installed location.
.LP
NFS mounting /var/dist simplifies our lives as long as the switch is up
and the NFS servers are fast.  When one of these assumptions fails to be true,
our old method of rsyncing /var/dist to head nodes, and dshing rdists on the
head nodes to the frames is probably superior.  Even on a good day, sending
out everything in /var/dist to all nodes of a 488-node SP is probably slower
than the old method.  Updates of small parts of /var/dist, however, really
scream now.
.LP
There should be some way to run 
.B "dist2 -l"
on  a node before the switch comes up.  Maybe a script that mounts /var/dist
over the ethernet temporarily, performs the update, and then unmounts it?
For this to work we would need a NetApp 100bT interface connected directly
to the SP ethernet router.  If invoked from an rc file on reboot, care should
be taken so it does not execute on a whole machine reboot to avoid saturating 
the ethernet.
.LP
.SH "SEE ALSO"
rdist(1), dist_all(1), dist_local(1)
