.\"
.\" $Id: dist_all.1,v 1.2 2001-07-14 05:36:52 garlick Exp $
.\" $Source: /g/g0/achu/temp/genders-cvsbackup-full/genders/dist_all.1,v $
.\"
.\" Copyright (C) 2000-2001 Regents of the University of California
.\" See the DISCLAIMER file distributed with this package.
.\"
.\" Author: Jim Garlick
.\" Adapted from IBM SP version for linux 4/00.
.\"
.TH DIST_ALL 1 "4/14/99" "LLNL" "DIST_ALL"
.SH NAME
dist_all \- master rdist script
.SH SYNOPSIS
.B dist_all
.I "[-r] [-w node[,node]] [package[.fileset]] ..."
.br
.B dist_all
.I "-l"
.SH DESCRIPTION
The purpose of 
.B dist_all
is to broadcast files from the /var/dist rdist repository to nodes of an SP
system.  In the absense of the 
.I -r 
option, it executes
.B "dist2 -l"
on all nodes plus the CWS.  
.B "dist2"
in turn runs rdist against files located in the NFS-mounted rdist repository,
/var/dist.
.LP
As NFS access to /var/dist requires the SP switch to be operational, the
.I -r
option is provided for running 
.B "dist2"
on the CWS and using rdist protocol to update the nodes via ethernet.
This method runs in parallel to a lesser degree and is therefore much slower.
.LP
Any arguments not interpreted by 
.B "dist_all"
are passed on to 
.B "dist2".
Typically these include the names of packages/filesets or the 
.I -w
option and a list of nodes.
.LP
Packages are groups of files managed by a single Distfile in /var/dist, and 
filesets are labels within Distfiles.  If no packages are specified, everything
in /var/dist is sent out.  To get a list of valid packages, run
.B "dist_all -l"
.LP
The
.I -w
option takes a comma-separated list of nodes.  If no nodes are specified, all
nodes in the SP plus the CWS are assumed.  Nodes should always be specified
using initial_hostnames.  Use 
.I -r
to request that 
.B dist2
internally convert to reliable_hostnames.
.LP
.SH "SEE ALSO"
rdist(1), dist2(1)
