#!/bin/sh
#
# $Id: dist_all,v 1.5 2002-09-13 16:13:06 garlick Exp $
# $Source: /g/g0/achu/temp/genders-cvsbackup-full/genders/dist_all,v $
# 
# Copyright (C) 2000-2001 Regents of the University of California
# See the DISCLAIMER file distributed with this package.
#
# Author: Jim Garlick
# Adapted from IBM SP version for linux 4/00.
#
PATH=/admin/scripts:/admin/bin:$PATH
DIST=/usr/bin/dist2
FANOUT=32
NUMNODES=`nodeattr -n all|wc -l`

while [ $# -gt 0 ]; do
        case $1 in
		-l)
			ls -1 /var/dist/Distfile.* | sed 's/[^\.]*\.//'
			exit 0
			;;
		-r)
			NOSWITCH=1
			;;
                -w)     
			WOPT="-w$2"
			shift
                        ;;
                *)
			ARGS="$ARGS $1"
			;;
	esac
	shift
done

if [ $NOSWITCH ]; then
	$DIST $WOPT -r $ARGS
else
	# big system
	if [ $NUMNODES -gt 4 ]; then
		nodeattr -rn all | pdsh -b ${WOPT:-'-w-'} \
		    -f$FANOUT "$DIST -l "$ARGS"" | sed 's/[^:]*: //'

	# little system
	else
		$DIST $WOPT $ARGS
	fi
fi

exit 0
