#!/bin/sh
#
# $Id: dist_local,v 1.4 2002-09-13 16:13:06 garlick Exp $
# $Source: /g/g0/achu/temp/genders-cvsbackup-full/genders/dist_local,v $
#
# Copyright (C) 2000-2001 Regents of the University of California
# See the DISCLAIMER file distributed with this package.
# 
# Author: Jim Garlick
# Adapted from IBM SP version for linux 4/00.
#

exec /usr/bin/dist2 -l "$@"
