.\"
.\" $Id: dist_cmp.1,v 1.2 2001-07-14 05:36:52 garlick Exp $
.\" $Source: /g/g0/achu/temp/genders-cvsbackup-full/genders/dist_cmp.1,v $
.\"
.\" Copyright (C) 2000-2001 Regents of the University of California
.\" See the DISCLAIMER file distributed with this package.
.\"
.\" Author: Jim Garlick
.\" Adapted from IBM SP version for linux 4/00.
.\"
.TH DIST_CMP 1 "10/14/97" "LLNL" "DIST_CMP"
.SH NAME
dist_cmp \- compress rdist output
.SH SYNOPSIS
.B dist_all | dist_cmp
.br
.SH DESCRIPTION
.B Dist_cmp
is to 
.B dist_all 
what 
.B dshbak 
is to 
.B "dsh."
.B Dist_cmp
compresses 
.B rdist 
output and makes it more readable by:
.LP
1. Displaying all the output for a particular node on successive lines instead 
of in the order received.
.LP
2. Displaying only one copy of a line of output that is identical for multiple 
nodes, along with a list of nodes that produced this output.
.LP
3. Compressing long lists of node names that have numeric suffixes into ranges,
e.g. 
.I "blue001,blue002,blue003"
becomes
.I "blue001-003".
.LP
4. Separating multiple rdist sessions for a given node or list of nodes.
This is necessary as
.B dist_all 
updates mirror hosts twice:  once for the mirror, and once from the mirror
to the final destination.

.SH "SEE ALSO"
rdist(1), dist_all(1)
