.\"  
.\" $Id: inst.1,v 1.1.1.1 2001-04-25 21:01:50 garlick Exp $
.\" $Source: /g/g0/achu/temp/genders-cvsbackup-full/genders/inst.1,v $
.\"
.\" Copyright (C) 2000 Regents of the University of California
.\" See the DISCLAIMER file distributed with this package.  
.\"
.TH INST 1 "10/10/97" "LLNL" "INST"
.SH NAME
inst \- install files
.SH SYNOPSIS
.B inst
.I "-s file -d dstdir [-m mode] [-o owner] [-g group] [-c|-C] [-f] [-q]"
.br
.SH DESCRIPTION
.B Inst 
is similar to installbsd(1) but does not perform the install if it determines 
the destination file to be already up to date.
.LP
.B "-f" 
can be used to force the install.  If this option is not specified, a 
destination file with modification time equal to or greater than the source
file will not be overwritten.
.LP
.B "-c"
requests that the 
.I "cmp"
command be used to compare source and destination files, and to install only
if they do not match.
.LP
.B "-C"
requests that the
.I "diff -b"
command be used to compare source and destination files, and to install only
if they do not match.
.LP
.B "-q" causes
.I inst
to be verbose when installing files, and quiet otherwise (the reverse of the
default behavior).
.LP
If the
.B "-m,"
.B "-o,"
or
.B "-g"
options are not specified, the file is installed with the same mode, owner, 
or group, respectively, as the source file.

.SH "SEE ALSO"
install(1), installbsd(1)
