/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Genders */

#ifndef _Included_Genders
#define _Included_Genders
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Genders
 * Method:    genders_handle_setup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Genders_genders_1handle_1setup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
