/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Genders */

#ifndef _Included_Genders
#define _Included_Genders
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Genders
 * Method:    genders_constructor
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Genders_genders_1constructor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Genders
 * Method:    getnumnodes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Genders_getnumnodes
  (JNIEnv *, jobject);

/*
 * Class:     Genders
 * Method:    getnumattrs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Genders_getnumattrs
  (JNIEnv *, jobject);

/*
 * Class:     Genders
 * Method:    getmaxattrs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Genders_getmaxattrs
  (JNIEnv *, jobject);

/*
 * Class:     Genders
 * Method:    getnodename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Genders_getnodename
  (JNIEnv *, jobject);

/*
 * Class:     Genders
 * Method:    getnodes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Genders_getnodes__
  (JNIEnv *, jobject);

/*
 * Class:     Genders
 * Method:    getnodes
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Genders_getnodes__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Genders
 * Method:    getnodes
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Genders_getnodes__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
